name: Publish on main branch push

on: 
  push:
    branches:
      - "main"

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          registry-url: https://npm.pkg.github.com
          scope: "@adept-at"
      - name: npm install, lint, build, and test
        run: |
          npm ci
          npm run lint
          npm run build
          npm run test
      # publish when builds pass on the main branch
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          registry-url: https://npm.pkg.github.com
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
